version: '3'

services:
    api:
        container_name: api-backend
        build:
            context: ./api_service
        ports:
            - 5000:5000
        networks:
            - api-endpoint

    client:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8088:80"
        volumes:
            - ./website:/var/www/html 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - api
        networks:
            - api-endpoint

    # build:
    #     context: ./website
    # ports:
    #     - 8080:80
    # depends_on:
    #     - api
    # networks:
    #     - api-endpoint

networks:
  api-endpoint:
    driver: bridge