version: '3'
services:
    api:
        build:
            context: .
        ports:
            - 5000:5000
        volumes:
            - .:/opt/app
        networks:
            default:
                aliases:
                    - my-api.dev